-- CRIAÇÃO TABELA
create table employees (
    id number GENERATED by default as identity primary key,
    name VARCHAR2(150), 
    date_birth date,
    email varchar(100),
    job_title VARCHAR2(100)
);

-- INSERÇÃO DOS DADOS
insert into employees (name, date_birth, email, job_title)
    values ('Andressa Souza', '21/03/1999', 'andressa@email.com', 'Software Engineer');



